f.read()
print( f.read())
f.read()
f.readline()
print(f.readline())
f.readline()
print(f.readline())
f.readline()
for line in f:
    print(line, end='')
f.write('This is a test\n')
print(f.write('This is a test\n'))
f = open('workfile', 'rb+')
f.write(b'0123456789abcdef')
print(f.write(b'0123456789abcdef'))
f.seek(5)
print(f.seek(5))